parameters:
  bobv.entityhistory.table_prefix: _HISTORY_
  bobv.entityhistory.table_suffix: ~
  bobv.entityhistory.revision_field_name: rev
  bobv.entityhistory.revision_type_field_name: revtype
  bobv.entityhistory.entities: {}

services:
  bobv.entityhistory.configuration:
    class: BobV\EntityHistoryBundle\Configuration\HistoryConfiguration
    calls:
      - [injectVars, [ "%bobv.entityhistory.table_prefix%", "%bobv.entityhistory.table_suffix%", "%bobv.entityhistory.revision_field_name%", "%bobv.entityhistory.revision_type_field_name%", "%bobv.entityhistory.entities%" ]]

  bobv.entityhistory.create_schema_subscriber:
    class: BobV\EntityHistoryBundle\EventSubscriber\CreateSchemaSubscriber
    arguments: [ "@bobv.entityhistory.configuration" ]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  bobv.entityhistory.log_history_subscriber:
    class: BobV\EntityHistoryBundle\EventSubscriber\LogHistorySubscriber
    arguments: [ "@bobv.entityhistory.configuration" ]
    tags:
      - { name: doctrine.event_subscriber, connection: default }
